# Generated by Django 4.2.6 on 2023-10-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ecolage_eleve_formateur_formation_module_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecolage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salle',
            options={},
        ),
    ]
