# Generated by Django 4.2.6 on 2023-10-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ecolage_formateur_formation_module_salle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecolage',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.DeleteModel(
            name='Formateur',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
