# Generated by Django 4.2.6 on 2023-11-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ecolage_formateur_formation_module_salle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.CharField(db_column='Photo', max_length=255),
        ),
        migrations.AlterField(
            model_name='formation',
            name='id_formateur',
            field=models.ForeignKey(db_column='Id_Formateur', on_delete=django.db.models.deletion.CASCADE, to='home.formateur'),
        ),
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.CharField(db_column='Photo', max_length=255),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id_ecolage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id_eleve',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='photo',
            field=models.ImageField(upload_to='media/Photo_Eleve'),
        ),
    ]
