# Generated by Django 4.2.6 on 2023-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_paiement_id_alter_eleve_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='id',
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_paiement',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
