# Generated by Django 4.2.6 on 2023-11-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_paiement_id_paiement_id_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id_ecolage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ecolage'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.eleve'),
        ),
    ]
